pipeline {
    agent any

    environment {
        VENV_DIR = "venv"
        BASE_URL = credentials('BASE_URL')
        USERNAME = credentials('USERNAME')
        PASSWORD = credentials('PASSWORD')
    }

    stages {
        stage('Clone') {
            steps {
                echo 'Cloning repository...'
            }
        }

        stage('Setup Python') {
            steps {
                sh '''
                    python3 -m venv $VENV_DIR
                    . $VENV_DIR/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                    playwright install
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    export BASE_URL=$BASE_URL
                    export USERNAME=$USERNAME
                    export PASSWORD=$PASSWORD

                     . $VENV_DIR/bin/activate
                    pytest --html=reports/report.html
                '''
            }
        }

        stage('Publish Report') {
            steps {
                publishHTML(target: [
                    allowMissing: false,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'reports',
                    reportFiles: 'report.html',
                    reportName: "Playwright Test Report"
                ])
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/reports/*.html', allowEmptyArchive: true
        }
    }
}
